#!/usr/bin/env node

// dotenv/config must be imported first so env vars are loaded before anything reads them
import 'dotenv/config';
import { mkdirSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import OpenAI from 'openai';
import { CliDisplayExit, parseCli } from './cli.js';
import { fetchVideoMetadata, fetchTranscript } from './youtube.js';
import { summarizeWithProvider } from './summarizer.js';
import {
  createCodexSummaryProvider,
  createOpenAiSummaryProvider,
  detectCodexChatGptLogin,
  type SummaryProvider,
} from './summary-provider.js';
import { generateMarkdown, writeMarkdownFile } from './markdown.js';
import { renderTranscriptText } from './transcript.js';
import type {
  CliOptions,
  ExtractOutput,
  PipelineMode,
  SummaryData,
  TranscriptResult,
} from './types.js';
import { AppError } from './types.js';

const JSON_SCHEMA_VERSION = 1 as const;

// Pre-parse flags so even CLI parsing failures use the requested output mode.
let jsonMode = process.argv.includes('--json');
const requestedMode: PipelineMode = process.argv.includes('--extract-only')
  ? 'extract'
  : 'full';

function configureYtdlEnvironment(): void {
  process.env['YTDL_NO_UPDATE'] ??= '1';

  if (process.env['YTDL_DEBUG_PATH']) {
    return;
  }

  // Avoid writing into cwd so --help/--version work from read-only directories.
  const ytdlCacheDir = path.join(os.tmpdir(), 'youtube2md', 'ytdl');
  try {
    mkdirSync(ytdlCacheDir, { recursive: true });
    process.env['YTDL_DEBUG_PATH'] = ytdlCacheDir;
  } catch {
    // Best-effort only. Continue without custom debug path.
  }
}

configureYtdlEnvironment();

/** Priority: --out > --out-dir/<videoId>.<ext> > ./summaries/<videoId>.<ext>. */
function computeOutputPath(videoId: string, opts: CliOptions, ext: string): string {
  if (opts.out) return path.resolve(opts.out);
  const dir = opts.outDir
    ? path.resolve(opts.outDir)
    : path.resolve(process.cwd(), 'summaries');
  return path.join(dir, `${videoId}.${ext}`);
}

function transcriptResultFields(transcript: TranscriptResult): {
  transcriptSource: TranscriptResult['source'];
  actualLanguage: string | null;
  autoGeneratedCaptions: boolean | null;
} {
  return {
    transcriptSource: transcript.source,
    actualLanguage: transcript.languageCode ?? null,
    autoGeneratedCaptions: transcript.autoGenerated ?? null,
  };
}

function writeArtifact(filePath: string, content: string): void {
  try {
    mkdirSync(path.dirname(filePath), { recursive: true });
    writeFileSync(filePath, content, 'utf-8');
  } catch (err) {
    throw new AppError('E_WRITE_FAILED', String(err));
  }
}

function emitJson(value: unknown): void {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`);
}

// ─── Extract pipeline ─────────────────────────────────────────────────────────

async function runExtractPipeline(opts: CliOptions): Promise<void> {
  const { videoId } = opts;
  const apiKey = process.env['OPENAI_API_KEY']?.trim();
  // captions-only is a hard policy boundary even when a key exists in the env.
  const whisperClient = apiKey && !opts.captionsOnly ? new OpenAI({ apiKey }) : null;

  console.log(`Processing video: ${videoId}`);
  console.log('Fetching video metadata...');
  const metadata = await fetchVideoMetadata(videoId);
  console.log(`Title: "${metadata.title}" | Duration: ${metadata.duration}`);

  console.log('Fetching transcript...');
  const transcript = await fetchTranscript(videoId, whisperClient, {
    preferredLanguage: opts.captionLang,
    captionsOnly: opts.captionsOnly,
  });
  console.log(
    `Transcript fetched: ${transcript.segments.length} segments via ${transcript.source}.`
  );

  const commonResult = {
    schemaVersion: JSON_SCHEMA_VERSION,
    ok: true as const,
    mode: 'extract' as const,
    videoId,
    metadata,
    ...transcriptResultFields(transcript),
  };

  let artifact: string;
  let extension: 'json' | 'txt';

  if (opts.extractFormat === 'json') {
    const payload: ExtractOutput = {
      ...commonResult,
      extractFormat: 'json',
      segments: transcript.segments,
    };
    artifact = `${JSON.stringify(payload, null, 2)}\n`;
    extension = 'json';
  } else {
    artifact = renderTranscriptText(transcript.segments, opts.extractFormat);
    extension = 'txt';
  }

  if (opts.stdout) {
    if (opts.json && opts.extractFormat !== 'json') {
      emitJson({
        ...commonResult,
        extractFormat: opts.extractFormat,
        text: artifact,
      });
    } else {
      process.stdout.write(artifact);
    }
    return;
  }

  const outPath = computeOutputPath(videoId, opts, extension);
  writeArtifact(outPath, artifact);

  if (opts.json) {
    emitJson({
      ...commonResult,
      extractFormat: opts.extractFormat,
      outputPath: outPath,
    });
  } else {
    console.log(`\nExtract complete! Written to:\n  ${outPath}`);
  }
}

// ─── Full pipeline ────────────────────────────────────────────────────────────

interface ProviderSetup {
  providers: SummaryProvider[];
  fallbackUsed: boolean;
}

async function configureSummaryProviders(
  opts: CliOptions,
  openai: OpenAI | null
): Promise<ProviderSetup> {
  const providers: SummaryProvider[] = [];
  let fallbackUsed = false;

  if (opts.provider !== 'openai') {
    const codexAvailability = await detectCodexChatGptLogin();
    if (codexAvailability.available) {
      try {
        providers.push(await createCodexSummaryProvider());
      } catch (err) {
        if (opts.provider === 'codex') {
          throw new AppError(
            'E_SUMMARIZER_UNAVAILABLE',
            `Codex SDK initialization failed: ${String(err)}`
          );
        }
        fallbackUsed = true;
        console.warn(`Codex SDK initialization failed: ${String(err)}`);
      }
    } else if (opts.provider === 'codex') {
      throw new AppError(
        'E_SUMMARIZER_UNAVAILABLE',
        codexAvailability.reason ?? 'Codex provider is unavailable.'
      );
    } else {
      fallbackUsed = true;
      console.log(`Codex SDK unavailable: ${codexAvailability.reason}`);
    }
  }

  if (opts.provider !== 'codex') {
    if (openai) {
      providers.push(createOpenAiSummaryProvider(openai));
    } else if (opts.provider === 'openai') {
      throw new AppError(
        'E_OPENAI_AUTH',
        '--provider openai requires OPENAI_API_KEY.'
      );
    }
  }

  if (providers.length === 0) {
    throw new AppError(
      'E_SUMMARIZER_UNAVAILABLE',
      'No summarization provider is available.\n' +
        'Install @openai/codex-sdk and log in with ChatGPT, or set OPENAI_API_KEY.\n' +
        'Tip: use --extract-only to fetch transcripts without a summarizer.'
    );
  }

  return { providers, fallbackUsed };
}

async function runFullPipeline(opts: CliOptions): Promise<void> {
  const apiKey = process.env['OPENAI_API_KEY']?.trim();
  const openai = apiKey ? new OpenAI({ apiKey }) : null;
  const model = opts.model ?? process.env['OPENAI_MODEL'] ?? 'gpt-5.6-luna';
  const providerSetup = await configureSummaryProviders(opts, openai);
  const { videoId } = opts;

  console.log(`Processing video: ${videoId}`);
  console.log('Fetching video metadata...');
  const metadata = await fetchVideoMetadata(videoId);
  console.log(`Title: "${metadata.title}" | Duration: ${metadata.duration}`);
  if (metadata.nativeChapters.length > 0) {
    console.log(`Found ${metadata.nativeChapters.length} native YouTube chapter(s).`);
  }

  console.log('Fetching transcript...');
  const transcript = await fetchTranscript(
    videoId,
    opts.captionsOnly ? null : openai,
    {
      preferredLanguage: opts.captionLang,
      captionsOnly: opts.captionsOnly,
    }
  );
  const { segments } = transcript;
  console.log(
    `Transcript fetched: ${segments.length} segments via ${transcript.source}.`
  );

  if (opts.lang) {
    console.log(`Summary language override: ${opts.lang}`);
  } else {
    console.log('Summary language: same as transcript');
  }

  let gptResult: Awaited<ReturnType<typeof summarizeWithProvider>> | undefined;
  let selectedProvider: SummaryProvider | undefined;
  const providerFailures: Array<{ provider: SummaryProvider; error: unknown }> = [];

  for (const [index, provider] of providerSetup.providers.entries()) {
    console.log(`Summarization provider: ${provider.name}`);
    try {
      gptResult = await summarizeWithProvider(
        provider,
        segments,
        metadata,
        model,
        opts.lang
      );
      selectedProvider = provider;
      break;
    } catch (err) {
      providerFailures.push({ provider, error: err });
      const nextProvider = providerSetup.providers[index + 1];
      if (nextProvider) {
        providerSetup.fallbackUsed = true;
        console.warn(
          `${provider.name} failed; falling back to ${nextProvider.name}.\n` +
            `Details: ${String(err)}`
        );
      }
    }
  }

  if (!gptResult || !selectedProvider) {
    throwProviderFailure(providerFailures);
  }

  console.log(
    `Summary complete via ${selectedProvider.name}: ` +
      `${gptResult.chapters.length} chapters detected.`
  );

  const summaryData: SummaryData = {
    metadata,
    transcriptSource: transcript.source,
    summary: gptResult.summary,
    chapters: gptResult.chapters,
    takeaways: gptResult.takeaways,
  };
  const markdown = generateMarkdown(summaryData);
  const commonResult = {
    schemaVersion: JSON_SCHEMA_VERSION,
    ok: true as const,
    mode: 'full' as const,
    videoId,
    metadata,
    ...transcriptResultFields(transcript),
    provider: selectedProvider.kind,
    fallbackUsed: providerSetup.fallbackUsed,
  };

  if (opts.stdout) {
    if (opts.json) {
      emitJson({ ...commonResult, markdown });
    } else {
      process.stdout.write(markdown);
    }
    return;
  }

  const outPath = computeOutputPath(videoId, opts, 'md');
  try {
    writeMarkdownFile(outPath, markdown);
  } catch (err) {
    throw new AppError('E_WRITE_FAILED', String(err));
  }

  if (opts.json) {
    emitJson({ ...commonResult, outputPath: outPath });
  } else {
    console.log(`\nDone! Summary written to:\n  ${outPath}`);
  }
}

function throwProviderFailure(
  failures: Array<{ provider: SummaryProvider; error: unknown }>
): never {
  const details = failures
    .map(({ provider, error }) => `  - ${provider.name}: ${String(error)}`)
    .join('\n');
  const openAiFailure = failures.find(({ provider }) => provider.kind === 'openai');
  if (openAiFailure) {
    const message = String(openAiFailure.error);
    if (message.includes('401') || /invalid.api.key/i.test(message) || /authentication/i.test(message)) {
      throw new AppError('E_OPENAI_AUTH', message);
    }
    if (message.includes('429') || /rate.limit/i.test(message)) {
      throw new AppError('E_OPENAI_RATE_LIMIT', message);
    }
  }

  throw new AppError(
    'E_SUMMARIZER_UNAVAILABLE',
    `All configured summarization providers failed.\n${details}`
  );
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const opts = parseCli();
  jsonMode = opts.json;

  // Progress always stays on stderr when stdout is a data channel.
  if (opts.json || opts.stdout) {
    console.log = (...args: unknown[]) => console.error(...args);
  }

  if (opts.extractOnly) {
    await runExtractPipeline(opts);
  } else {
    await runFullPipeline(opts);
  }
}

main().catch((err) => {
  if (err instanceof CliDisplayExit) {
    process.exitCode = err.exitCode;
    return;
  }

  const appError = err instanceof AppError
    ? err
    : new AppError('E_UNKNOWN', String(err));

  if (jsonMode) {
    emitJson({
      schemaVersion: JSON_SCHEMA_VERSION,
      ok: false,
      mode: requestedMode,
      code: appError.code,
      message: appError.message,
    });
  } else {
    process.stderr.write(`Error [${appError.code}]: ${appError.message}\n`);
  }
  process.exitCode = 1;
});
